default_platform(:ios)

platform :ios do
  
  # === API Key loader ===
  def asc_api_key
    app_store_connect_api_key(
      key_id: "#{ENV['APP_KEY_ID']}",
      issuer_id: "#{ENV['APP_ISSUER_ID']}",
      key_filepath: "#{ENV['APP_KEY_PATH']}",
      duration: 1200,
      in_house: false
    )
  end

  desc "Create app on Apple Developer and App Store Connect"
  lane :create_app do
    produce  
  end

  desc "Sync certificates"
  lane :sync_profiles do
    match(readonly: true, type: "appstore")
  end

  desc "Create ipa"
  lane :build do
    sync_profiles
    increment_build_number
    gym
  end

  desc "Upload to TestFlight"
  lane :beta do
    run_unit_tests
    asc_api_key
    build
    pilot(
      skip_waiting_for_build_processing: false
    )
  end

  desc "Run all the tests"
  lane :run_unit_tests do
    scan(
      scheme: "Just ToDo",
      clean: true,
      devices: ["iPhone 16"]
      )
    end

  desc "Take screenshots"
  lane :screenshot do
    snapshot
  end

  desc "Upload to App Store"
  lane :upload do
    asc_api_key          # <--- REQUIRED
    deliver
  end

  desc "Create app, screenshot ,build and upload"
  lane :release_app do
    create_app
    build
    screenshot	
    asc_api_key          # <--- REQUIRED
    deliver
  end

  # desc "Demo using different .env files print sample"
  # lane :sampleTest do
  #     # sampleTest
  #     print "Current app Id = #{ENV['APP_ID']} and api key = #{ENV['API_KEY']}"
  #     # You can add other commands here
  # end

end
